server:
  port: 10112

#Request Call 관련 항목
uri:
  api: fourhealth
  version: v0.1
  resource: graphql


#GraphQL 관련 항목
graphql:
  path: /Users/jeongho/Documents/Develop/fourhealth_dev/fourhealth/src/main/resources/graphql_resource
  files: schema.graphql


#DataSource
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://kjc0411.cafe24.com:3306
    username: kjc0411
    password: ksmart37!!
    connection-timeout: 10000
    validation-timeout: 10000
    maxLifetime: 580000
    maximumPoolSize: 30
    minimumIdle: 10


#FoodAPIInfo
foodapi:
  datatype: json
  serviceId:
    ingredient:
      key: I2790
    healthfood:
      key: I0760
    recipe:
      key: COOKRCP01
  validation:
    key: 910606a0c65e48fb9339
  basicurl:
    url: http://openapi.foodsafetykorea.go.kr/api/


#    // 인증키 String keyId = "910606a0c65e48fb9339";
#    // url 기본 : String url =
#    // "http://openapi.foodsafetykorea.go.kr/api/keyId/serviceId/dataType/startIdx/endIdx";
#    // url 값 인자가 필요할 경우
#    // http://openapi.foodsafetykorea.go.kr/api/인증키/서비스명/요청파일타입/요청시작위치/요청종료위치/변수명=값&변수명=값2
#    // e.g) http://openapi.foodsafetykorea.go.kr/api/sample/I2790/xml/1/5/DESC_KOR=값
#    // &RESEARCH_YEAR=값 &MAKER_NAME=값
#    // 서비스 아이디 키값
#    // 식품영양성분 : I2790
#    // 식품레시피 : COOKRCP01
#    // 건강기능식품 : I0760